[production]
10.50.49.46 ansible_user=rahul12 ansible_connection=local ansible_become_password=Rahul@1606

[staging]
# Empty for now

[local]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'